### ISSUE TITLE
MITRE ATT&CK Compliance Lookup Gen No Results

### ISSUE THREAD

**Issue by arsenedhani** [seynur/DA-ESS-MitreContent#37]
Hi Seynur,

I have an issue with Mitre Att&ck Splunk Apps, I'm using Splunk version 9.1 and Mitre Att&ck Apps version 3.9.0, there is no results for compliance lookup gen, I already run manually the save search but still not working
Any thoughts on how to troubleshoot?

![image](https://github.com/seynur/DA-ESS-MitreContent/assets/144196168/c55ff7b2-200b-4979-b182-ed0777c10e73)

Thank you

**Comment by selimseynur** [comment]
Hello,

You can also send an email to development@seynur.com for support regarding this app.

The app utilizes outputlookup command to create/overwrite CSV lookup files.  As per Splunk documentation (https://docs.splunk.com/Documentation/Splunk/latest/Security/SPLsafeguards), this command throws a warning before running it.  We're looking into converting these lookup files into KV Store lookups in the upcoming versions to bypass this issues.  Meanwhile, you can simple go to Configuration --> Lookup File Generation to create the lookup manually.  By default, a schedule search populates the lookup file daily.  I'm attaching several screenshots from the app to show the progress.
![lookupfilegeneration](https://github.com/seynur/DA-ESS-MitreContent/assets/8026309/c1cea58b-ca81-4aa4-acfc-aca968703b6d)
![lookupfilegeneration2](https://github.com/seynur/DA-ESS-MitreContent/assets/8026309/ffe0c028-3d1b-4379-a837-62a20ffde3e7)
![lookupfilegeneration3](https://github.com/seynur/DA-ESS-MitreContent/assets/8026309/5cb70a22-ed55-489e-9bcc-9ced5c01725a)
![lookupfilegeneration4](https://github.com/seynur/DA-ESS-MitreContent/assets/8026309/0a333ce7-df1d-48df-8090-c420871fb851)

Please let us know if this resolves your issue.
Best,
Selim

**Comment by selimseynur** [comment]
Hello,
Can you please send a separate email to development@seynur.com so that we can schedule a zoom session with you?

Thanks.
